<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <PropertyGroup>
        <ElsaVersion>3.6.0-preview.3976</ElsaVersion>
        <ElsaStudioVersion>3.6.0-preview.1286</ElsaStudioVersion>
        <ElsaExtensionsVersion>3.6.0-preview.177</ElsaExtensionsVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>
</Project>