<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup Label="Elsa">
        <PackageVersion Include="Elsa" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Alterations" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Alterations.Core" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Api.Client" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Api.Common" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Caching" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Common" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Dsl.ElsaScript" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Expressions" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Expressions.CSharp" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Expressions.Python" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Expressions.Liquid" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Expressions.JavaScript" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Expressions.JavaScript.Libraries" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Hosting.Management" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Http" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Identity" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.KeyValues" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Labels" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Mediator" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore.Common" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore.MySql" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore.Oracle" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore.PostgreSql" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore.Sqlite" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Persistence.EFCore.SqlServer" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Resilience" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Resilience.Core" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.SasTokens" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Scheduling" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Tenants" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Tenants.AspNetCore" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Workflows.Api" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Workflows.Core" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Workflows.Management" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Workflows.Runtime" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.Workflows.Runtime.Distributed" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.WorkflowProviders.BlobStorage" Version="$(ElsaVersion)"/>
        <PackageVersion Include="Elsa.WorkflowProviders.BlobStorage.ElsaScript" Version="$(ElsaVersion)"/>
    </ItemGroup>
    <ItemGroup Label="Elsa Extensions">
        <PackageVersion Include="Elsa.Actors.ProtoActor" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Alterations.MassTransit" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Caching.Distributed" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Caching.Distributed.MassTransit" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Caching.Distributed.ProtoActor" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.DropIns" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Email" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Http.Webhooks" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.OpenTelemetry" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Persistence.Dapper" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Persistence.Dapper.Migrations" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Persistence.MongoDb" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Retention" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.ServiceBus.AzureServiceBus" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.ServiceBus.MassTransit" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.ServiceBus.MassTransit.AzureServiceBus" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.ServiceBus.MassTransit.RabbitMq" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Scheduling.Hangfire" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Scheduling.Quartz" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Scheduling.Quartz.EFCore.MySql" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Scheduling.Quartz.EFCore.PostgreSql" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Scheduling.Quartz.EFCore.Sqlite" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Scheduling.Quartz.EFCore.SqlServer" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Sql" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Sql.MySql" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Sql.PostgreSql" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Sql.Sqlite" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Sql.SqlServer" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Workflows.Runtime.ProtoActor" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.WorkflowContexts" Version="$(ElsaExtensionsVersion)"/>
    </ItemGroup>
    <ItemGroup Label="Elsa Studio">
        <PackageVersion Include="Elsa.Studio" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Core.BlazorWasm" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Login.BlazorWasm" Version="$(ElsaStudioVersion)"/>
    </ItemGroup>
    <ItemGroup>
        <PackageVersion Include="DistributedLock" Version="2.7.1"/>
        <PackageVersion Include="Hangfire" Version="1.8.22"/>
        <PackageVersion Include="Hangfire.MemoryStorage" Version="1.8.1.2"/>
        <PackageVersion Include="Hangfire.PostgreSql" Version="1.20.12"/>
        <PackageVersion Include="Hangfire.SqlServer" Version="1.8.22"/>
        <PackageVersion Include="Hangfire.Storage.SQLite" Version="0.4.2"/>
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4"/>
        <PackageVersion Include="Microsoft.SemanticKernel" Version="1.68.0"/>
        <PackageVersion Include="Microsoft.SemanticKernel.Agents.Abstractions" Version="1.68.0" />
        <PackageVersion Include="Microsoft.SemanticKernel.Agents.Core" Version="1.68.0" />
        <PackageVersion Include="Microsoft.SemanticKernel.PromptTemplates.Handlebars" Version="1.68.0" />
        <PackageVersion Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.68.0-alpha" />
        <PackageVersion Include="Microsoft.SemanticKernel.Connectors.InMemory" Version="1.68.0-preview" />
        <PackageVersion Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-preview.251204.1" />
        <PackageVersion Include="Microsoft.Extensions.AI" Version="10.1.0" />
        <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-preview.251204.1" />
        <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.1.0-preview.1.25608.1" />
        <PackageVersion Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.251204.1" />
        <PackageVersion Include="Azure.AI.OpenAI" Version="2.7.0-beta.2" />
        <PackageVersion Include="Proto.Cluster.Kubernetes" Version="1.8.0"/>
        <PackageVersion Include="Proto.Persistence.Sqlite" Version="1.8.0"/>
        <PackageVersion Include="Proto.Persistence.SqlServer" Version="1.8.0"/>
        <PackageVersion Include="OpenTelemetry" Version="1.12.0"/>
        <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="1.12.0"/>
        <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0"/>
        <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.12.0-beta.1"/>
    </ItemGroup>
</Project>