<Project>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <PropertyGroup>
        <ElsaVersion>3.6.0-preview.3780</ElsaVersion>
        <ElsaStudioVersion>3.6.0-preview.1261</ElsaStudioVersion>
        <ElsaExtensionsVersion>3.6.0-preview.164</ElsaExtensionsVersion>
        <MicrosoftVersion>9.0.9</MicrosoftVersion>
        <ResilienceVersion>9.9.0</ResilienceVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>
</Project>