<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup Label="Elsa">
        <PackageVersion Include="Elsa.Api.Client" Version="$(ElsaVersion)"/>
    </ItemGroup>
    <ItemGroup Label="Elsa Extensions">
        <PackageVersion Include="Elsa.Actors.ProtoActor" Version="$(ElsaExtensionsVersion)"/>
        <PackageVersion Include="Elsa.Studio.Agents" Version="$(ElsaExtensionsVersion)"/>
    </ItemGroup>
    <ItemGroup Label="Elsa Studio">
        <PackageVersion Include="Elsa.Studio" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Core.BlazorServer" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Translations" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Dashboard" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Localization.BlazorServer" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Login.BlazorServer" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Login" Version="$(ElsaStudioVersion)"/>
        <PackageVersion Include="Elsa.Studio.Workflows" Version="$(ElsaStudioVersion)"/>
    </ItemGroup>
    <ItemGroup>
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4"/>
        <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="10.0.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components" Version="10.0.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0"/>
    </ItemGroup>
</Project>