<Project>
    
    <PropertyGroup>
        <ElsaVersion>3.6.0-preview.3976</ElsaVersion>
        <ElsaStudioVersion>3.6.0-preview.1286</ElsaStudioVersion>
        <ElsaExtensionsVersion>3.6.0-preview.177</ElsaExtensionsVersion>
    </PropertyGroup>

    <PropertyGroup>
        <UseProjectReferences>true</UseProjectReferences>
    </PropertyGroup>
</Project>