<Project>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <PropertyGroup>
        <ElsaVersion>3.6.0-preview.3192</ElsaVersion>
        <ElsaStudioVersion>3.6.0-preview.1165</ElsaStudioVersion>
        <ElsaExtensionsVersion>3.6.0-preview.113</ElsaExtensionsVersion>
        <MicrosoftVersion>9.0.7</MicrosoftVersion>
    </PropertyGroup>

    <PropertyGroup>
        <UseProjectReferences>false</UseProjectReferences>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>
</Project>